databases:
  - name: wild_loops
    databaseName: wild_loops
    user: henryescobar

services:
  - type: web
    name: wilder
    runtime: ruby
    env: production
    repo: https://github.com/pnw-henry/wild-loops
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wild_loops
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
